Repository DeveloperAcademy-POSTECH/2025-SSG-M4, pull requests merged in 2025-06, with the labels that each got.

#22 docs: 2주차 스터디 작성
  Kave/Swift Study.md
  Kave/Week1/주석 (Comments).md
  Kave/Week2/부울.md
  Kave/Week2/숫자 타입 변환.md
  Kave/Week2/타입 별칭.md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#27 docs: 2주차 스터디 내용
  Jenki/Week2/10. 부울 (Booleans).md
  Jenki/Week2/8. 숫자 타입 변환 (Numeric Type Conversion).md
  Jenki/Week2/9. 타입 별칭 (Type Aliases).md
  Jenki/Week3/xcodeproj 파일 이슈.md
  Jenki/무제.md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#30 docs: Week3 학습내용 작성
  Wonjun/Assets/스크린샷 2025-06-08 오후 5.05.36.png
  Wonjun/Assets/스크린샷 2025-06-08 오후 5.15.41.png
  Wonjun/Assets/스크린샷 2025-06-08 오후 9.56.23.png
  Wonjun/Week3/FetchDescriptor.md
  Wonjun/Week3/Week3 Index.md
  Wonjun/Week3/제약조건.md
  Wonjun/Week3/최적화 옵션.md
  Wonjun/Week3/페이지네이션.md
Labels: 🤗 리뷰 기다리는 중

#29 docs: 3주차 스터디 - ContentView, navigation관련 트러블슈팅
  Finn/Assets/IMG_3013.png
  Finn/Assets/IMG_C4C8D6B48E4E-1.jpeg
  Finn/Assets/Kapture 2025-06-05 at 21.16.40.gif
  Finn/Assets/스크린샷 2025-06-08 오후 9.14.28.png
  Finn/Easel/NavigationStackRoot.excalidraw.md
  Finn/Finn`s Note.md
  Finn/Week3/ContentView에 대하여.md
  Finn/추가개념/Router.swift.md
  Finn/추가개념/WindowGroup-ContentView.md
  Finn/추가개념/active, inactive, background.md
  Finn/추가개념/데이터삭제로직.md
Labels: 🤗 리뷰 기다리는 중

#23 docs: 2주차 내용(숫자타입변환, 타입 별칭, 부울)
  Bear/Basic Swift.md
  Bear/Week2/1. 숫자 타입 변환 (Numeric Type Conversion).md
  Bear/Week2/2. 타입 별칭 (Type Aliases).md
  Bear/Week2/3. 불 (Booleans).md
  Bear/Week3/Core Data.md
  무제.canvas
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#31 docs: 3주차 학습내용 작성
  Kave/Assets/UIKit-ContextMenu.png
  Kave/Assets/UIKit-MVC.png
  Kave/Assets/UIKit-practice.png
  Kave/Assets/components-context-menu.png
  Kave/Assets/context-menu-section.png
  Kave/Assets/context-menu-swiftui.png
  Kave/Swift Study.md
  Kave/Week3/Practice/ContextMenu.swift
  Kave/Week3/Practice/UIKitPractice.swift
  Kave/Week3/UIKit.md
  Kave/Week3/빠른 메뉴 (Context Menu).md
Labels: 📚 회고, 🤗 리뷰 기다리는 중

#28 Hyun/docs: Week3 NavigationManager
  Hyun/Week3/@Published.md
  Hyun/Week3/@StateObject.md
  Hyun/Week3/NavigationManager.md
  Hyun/Week3/ObservableObject.md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#36 Week4/SwfitUI animation 사용법/ Week5/함수(Functions)의 핵심 개념 복습 및 정리함수
  Bear/100days SwiftUI/7days.md
  Bear/Week4/Swift UI 애니메이션.md
  Bear/Week5/함수(Functions)의 핵심 개념 복습 및 정리함수.md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#32 hyun/4주차-Tuist
  Hyun/Assets/Tuist Github Main Image.jpg
  Hyun/Assets/header.jpg
  Hyun/Week4/Tuist.md
  Hyun/Week4/모듈(Module).md
  Hyun/Week4/오픈 소스(Open Source).md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#38 hyun/5주차
  Hyun/Week5/음량 감지.md
Labels: 📋 문서작업, 🤗 리뷰 기다리는 중

#37 Jenki/Week4(OCR Manager) + Jenki/Week5(OCRTextParser)
  Jenki/Assets/Pasted image 20250624164354.png
  Jenki/Week4/OCR Manager.md
  Jenki/Week5/OCRTextParser.md
Labels: 🤗 리뷰 기다리는 중
