Repository DeveloperAcademy-POSTECH/2025-SSG-M4, pull requests merged in 2025-05, with the labels that each got.

#11 docs: PR 다중 템플릿 구조 적용
  .github/PULL_REQUEST_TEMPLATE/docs-fix.md
  .github/PULL_REQUEST_TEMPLATE/learning-note.md
  .github/PULL_REQUEST_TEMPLATE/template-update.md
  .github/pull_request_template.md
  Finn/Week1/상수와 변수.md
Labels: 🛠 템플릿 업데이트

#16 docs: Week1 학습 내용 작성
  Wonjun/Assets/Pasted image 20250527173817.png
  Wonjun/Assets/Pasted image 20250527174139.png
  Wonjun/Private/마크다운 사용법.md
  Wonjun/Week1/"주제".md
  Wonjun/Week1/1-1. 상수와 변수.md
  Wonjun/Week1/1-2. 주석과 세미콜론.md
  Wonjun/Week1/1-3. 정수.md
  Wonjun/Week1/1-4. 부동 소수점 숫자, 타입 세이프티와 타입 추론.md
  Wonjun/Week1/1-5. 숫자 리터럴.md
  Wonjun/Week1/Week1 Index.md
  Wonjun/코딩 테스트 swift 개념.md
Labels: 🤗 리뷰 기다리는 중

#17 [Docs] Week1 Swift-Basics
  Finn/Assets/스크린샷 2025-05-25 오후 2.04.40.png
  Finn/Assets/스크린샷 2025-05-25 오후 2.12.47.png
  Finn/Finn`s Note.md
  Finn/Week1/Basics.md
  Finn/Week1/문자열과 문자.md
  Finn/Week1/상수와 변수.md
  Finn/추가개념/Int vs UInt.md
  Finn/추가개념/Int.max 관련 문제.md
  Finn/추가개념/Type-safe.md
  Finn/추가개념/Week1 짜투리.md
  Finn/추가개념/값타입 vs 참조타입.md
  Finn/추가개념/문자열 삽입.md
  Finn/추가개념/부동 소수점.md
  Finn/추가개념/상수 선언.md
  Finn/추가개념/타입 추론 흐름.md
  Untitled.canvas
Labels: ✅ 리뷰 완료

#21 Bear
  Bear/100days SwiftUI/4days.md
  Bear/100days SwiftUI/5days.md
  Bear/100days SwiftUI/6days.md
  Bear/100days SwiftUI/Hacking SwiftUI.md
  Bear/Basic Swift.md
  Bear/Week1/1. 상수와 변수 (Constants and Variables).md
  Bear/Week1/2. 주석 (Comments).md
  Bear/Week1/3. 세미콜론 (Semicolons).md
  Bear/Week1/4. 정수 (Integers).md
  Bear/Week1/5. 부동 소수점 숫자 (Floating-Point Numbers).md
  Bear/Week1/6. 타입 세이프티와 타입 추론 (Type Safety and Type Inference).md
  Bear/Week1/7. 숫자 리터럴 (Numeric Literals).md
  Docs/데이터 모델링 (Data Modeling).md
  LLVM 컴파일러.md
  Swift Standard Library.md
  Untitled.canvas
  병렬 처리(Swift-Concurrency).md
  열거형 (Enumeration).md
  옵셔널(Optionals).md
  정규식 DSL.md
  제네릭 (Generic).md
  클로저 (Closure).md
  프로토콜 지향 프로그래밍 (POP).md
Labels: ✅ 리뷰 완료
